# Funding & Sponsorship Options for Style Haven Clothing Shop
# Support the development and maintenance of this project

# GitHub Sponsors - Preferred method
github: [Mostafa-SAID7]

# Buy Me a Coffee - One-time or recurring support
buy_me_a_coffee: mssaid356p

# Ko-fi - Simple one-time donations
ko_fi: MostafaSaid

# Patreon - Monthly recurring support with exclusive perks
patreon: MostafaSaid

# Open Collective - Transparent community funding
open_collective: clothing-shop

# Liberapay - Recurring donations
liberapay: MostafaSaid

# IssueHunt - Fund specific issues and features
issuehunt: MostafaSaid

# Custom funding links
custom:
  - 'https://github.com/Mostafa-SAID7/clothing-shop'
  - 'https://www.paypal.me/MostafaSaid'
