# These are supported funding model platforms

github: 
  - Mostafa-SAID7        # Your GitHub Sponsors username

patreon: 
  MostafaSaid            # Your Patreon username

open_collective: 
  carcommunity           # Your Open Collective project name

ko_fi: 
  MostafaSaid            # Your Ko-fi username

tidelift: 
  npm/ccommunity         # Example: Tidelift package/platform name

community_bridge: 
  carcommunity-project   # Example project name on Community Bridge

liberapay: 
  MostafaSaid            # Your Liberapay username

issuehunt: 
  MostafaSaid            # Your IssueHunt username

lfx_crowdfunding: 
  carcommunity-project   # Example: LFX Crowdfunding project name

polar: 
  carcommunity           # Your Polar username

buy_me_a_coffee: 
  mssaid356p            # Your Buy Me a Coffee username

thanks_dev: 
  MostafaSaid            # Your thanks.dev username

custom: 
  - 'https://yourcompany.com/sponsor'
  - 'https://yourportfolio.com/support'
